<?php

namespace AppBundle\Repository;

/**
 * vipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class vipRepository extends \Doctrine\ORM\EntityRepository
{
}
